import { useState } from 'react';
import { Alert, Button, Col, Container, Form, Row } from 'react-bootstrap';
import SectionTitle from '../components/SectionTitle';
import { useLanguage } from '../context/LanguageContext';
import '../styles/pages/common-page.css';
import '../styles/pages/contact.css';

export default function Contact() {
  const [sent, setSent] = useState(false);
  const { isArabic } = useLanguage();
  const submitForm = (event) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); };
  return <><section className="page-hero page-hero--contact"><Container><span className="eyebrow text-white-50">{isArabic ? 'نحن هنا للمساعدة' : 'We are here to help'}</span><h1>{isArabic ? 'تحدث مع فريق رحلتي' : 'Talk to the Rihlati team'}</h1><p>{isArabic ? 'أرسل سؤالك حول الحجز أو الوجهات أو المساعدة أثناء السفر.' : 'Send a question about bookings, destinations, or travel assistance.'}</p></Container><div className="shape-divider shape-divider--page" aria-hidden="true"><span /><span /><span /></div></section><section className="section-space page-soft-bg"><Container><Row className="g-5 align-items-start"><Col lg={5}><SectionTitle centered={false} eyebrow={isArabic ? 'تواصل معنا' : 'Contact us'} title={isArabic ? 'دعنا نجعل رحلتك أسهل' : 'Let us make your journey easier'} text={isArabic ? 'فريقنا جاهز للإجابة عن أسئلتك المتعلقة بالسفر.' : 'Our team is ready to help with your travel questions.'} /><div className="contact-list"><div><i className="bi bi-telephone-fill" /><span><strong>{isArabic ? 'اتصل بنا' : 'Call us'}</strong>+971 4 555 0101</span></div><div><i className="bi bi-envelope-fill" /><span><strong>{isArabic ? 'البريد الإلكتروني' : 'Email'}</strong>hello@rihlati.demo</span></div><div><i className="bi bi-geo-alt-fill" /><span><strong>{isArabic ? 'المكتب' : 'Office'}</strong>{isArabic ? 'دبي، الإمارات العربية المتحدة' : 'Dubai, United Arab Emirates'}</span></div></div></Col><Col lg={7}><Form className="contact-form" onSubmit={submitForm}><Row className="g-3"><Col md={6}><Form.Label>{isArabic ? 'الاسم الكامل' : 'Full name'}</Form.Label><Form.Control required placeholder={isArabic ? 'اسمك' : 'Your name'} /></Col><Col md={6}><Form.Label>{isArabic ? 'البريد الإلكتروني' : 'Email address'}</Form.Label><Form.Control type="email" required placeholder="name@example.com" /></Col><Col xs={12}><Form.Label>{isArabic ? 'الموضوع' : 'Subject'}</Form.Label><Form.Control required placeholder={isArabic ? 'كيف يمكننا مساعدتك؟' : 'How can we help?'} /></Col><Col xs={12}><Form.Label>{isArabic ? 'الرسالة' : 'Message'}</Form.Label><Form.Control as="textarea" rows={6} required placeholder={isArabic ? 'اكتب رسالتك' : 'Write your message'} /></Col><Col xs={12}><Button type="submit" className="primary-action">{isArabic ? 'إرسال الرسالة' : 'Send message'}</Button></Col></Row>{sent && <Alert variant="success" className="mt-3 mb-0">{isArabic ? 'شكرًا لك. تم إرسال رسالتك التجريبية بنجاح.' : 'Thank you. Your demo message has been submitted successfully.'}</Alert>}</Form></Col></Row></Container></section></>;
}
